# Importance of Numpy :-

# Arrays :-

==> Arrays only consists of elements belonging to the same data type.
==> Less flexible since addition, deletion has to be done element wise.

In [2]:
import numpy as np      # {as - alias}

In [4]:
# Ex-1.

x = np.array([1,2,3,4,5])
print(x)
print(type(x))               # ndarray = n dimention array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Ex-2.

l = [1,2,3,4,5,6]
print(l,"\n",type(l))

[1, 2, 3, 4, 5, 6] 
 <class 'list'>


# Array is faster than list :-

In [17]:
%timeit [i**5 for i in range(1,10)]

1.37 μs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
import numpy as np

%timeit np.arange(1,10)**5

3.06 μs ± 613 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating numpy arrays :-

In [21]:
# Ex-

x = np.array([45,25,65])
print(x)
print(type(x))
print(x.ndim)              # ndim : use to find array dimention.      1 - dimentional array

[45 25 65]
<class 'numpy.ndarray'>
1


In [23]:
x = np.array([[45,25,76]])
print(x)
print(type(x))
print(x.ndim)               # 2 - dimention array

[[45 25 76]]
<class 'numpy.ndarray'>
2


In [24]:
x = np.array([[[45,25,76]]])
print(x)
print(type(x))
print(x.ndim)               # 3 - dimention array

[[[45 25 76]]]
<class 'numpy.ndarray'>
3


In [27]:
# Ex - 

import numpy as np

m = []
for i in range(1,5):
    num = input("Enter number : ")
    m.append(num)
y = np.array(m)
print(y)
print(type(y))

Enter number :  12
Enter number :  15
Enter number :  17
Enter number :  19


['12' '15' '17' '19']
<class 'numpy.ndarray'>


# Creating 2-d array :-

In [50]:
# Ex-

ar2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ar2)
print(type(ar2))
print()
print(ar2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>

2


In [30]:
# Ex-

ar2 = np.array([[1,2,3,4],[5,6,7,8],[10,12,14]])
print(ar2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# Creating a 3-d array :-

In [49]:
# Ex-

ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(type(ar3))
print()
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
<class 'numpy.ndarray'>

3


# Creating a multi-dimention array :-

In [47]:
# Ex-

arn = np.array([1,2,3,4], ndmin=15)             # ndmin = number of dimention = 15
print(arn)
print()
print(arn.ndim)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]

15


In [48]:
# Ex-

arn = np.array(([1,2,3,4],[4,5,6,7]), ndmin=10)
print(arn,type(arn))
print()
print(arn.ndim)

[[[[[[[[[[1 2 3 4]
         [4 5 6 7]]]]]]]]]] <class 'numpy.ndarray'>

10


# Numpy array with all its elements value as zero :-

In [46]:
# Ex-

import numpy as np

ar = np.zeros(5)
print(ar)
print()
print(ar.ndim)

[0. 0. 0. 0. 0.]

1


In [45]:
ar1 = np.zeros((4,3))
print(ar1,type(ar1))
print()
print(ar1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>

2


In [52]:
ar2 = np.zeros((1,3,4))          # 1 : count, 3 : Row, 4 : Column
print(ar2),print()               # [[[    ]]]
print(ar2.ndim)                  # 012....

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

3


In [54]:
ar3 = np.zeros((2,3,4))
print(ar2)
print()
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

3


In [55]:
# Sol-1.

arr = np.ones(6)
print(arr)
print()
print(arr.ndim)

[1. 1. 1. 1. 1. 1.]

1


In [56]:
# Ex-

arr1 = np.ones((4,5))
print(arr1)
print()
print(arr1.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

2


In [58]:
# Ex-

arr2 = np.ones((3,3,3))
print(arr2)
print()
print("The dimention is : ",arr2.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

The dimention is :  3


In [72]:
# Ex-

arr2 = np.ones((1,2,3), dtype = bool)
print(arr2)
print()
print("The dimention is : ",arr2.ndim)

[[[ True  True  True]
  [ True  True  True]]]

The dimention is :  3


# Creating an empty array :-

In [87]:
# Ex- 

import numpy as np

k = np.empty(3)           # Question
print(k)
print()
print(k.ndim)

[2.22e-322 1.24e-322 3.75e-322]

1


In [93]:
# Ex-

d = np.empty((4,4))      # Question
print(d)
print()
print(d.ndim)

[[4.67296746e-307 1.69121096e-306 1.69118787e-306 1.06809181e-306]
 [7.56599128e-307 1.11256817e-306 1.06811422e-306 1.42417221e-306]
 [1.11260619e-306 8.90094053e-307 1.86919378e-306 1.06809792e-306]
 [1.37962456e-306 1.69111861e-306 1.78020169e-306 7.56605918e-307]]

2


# Creating an array with range :-

In [96]:
# Ex-

b = np.arange(1,21)      # {n = n-1} 21-1 = 20
print(b)
print()
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

1


In [99]:
# Ex-

a = np.arange(3,101,3)          # (start : End : Update)
print(a)
print()
print(a.ndim)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]

1


In [100]:
a = np.arange(5,61,5)
print(a)
print()
print(a.ndim)

[ 5 10 15 20 25 30 35 40 45 50 55 60]

1


# linspace :-

In [101]:
# Ex -

a = np.linspace(1,10,5)   # Question
print(a)
print()
print(a.ndim)

[ 1.    3.25  5.5   7.75 10.  ]

1


In [109]:
# Ex-

b = np.linspace(1,30,8)
print(b)
print()
print(b.ndim)

[ 1.          5.14285714  9.28571429 13.42857143 17.57142857 21.71428571
 25.85714286 30.        ]

1


In [110]:
c = np.linspace(5,20,6)
print(c)

[ 5.  8. 11. 14. 17. 20.]


# Shape function :-

In [113]:
# Ex -

ar = np.array([[1,2,3],[10,11,13]])
print(ar)
print()
print(ar.ndim)
print(ar.shape)         # (2,3) --> 2 = Row, 3 = Coloumn

[[ 1  2  3]
 [10 11 13]]

2
(2, 3)


In [116]:
# Ex - 

ar = np.array([[1,2,3],[10,11,13],[15,16,17]])
print(ar)
print()
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [10 11 13]
 [15 16 17]]

2
(3, 3)


In [118]:
# Ex - 

ar = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(ar)
print()
print(ar.ndim)
print(ar.shape)             # [[[   ]]]  --> 0 1 2 3 4 ...........

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

3
(1, 4, 3)


# Reshape function :-

In [119]:
# Ex - 

m = np.array([1,2,3,4,5,6,7,8,9,10])
n = m.reshape(2,5)
print(n)
print()
print(m)
print()
print(n.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]

2


In [122]:
# Ex - 

m = np.array([1,2,3,4,5,6,7,8,9])     # 10 numbers not accept because shape is fixed and same elements in the array.
n = m.reshape(3,3)
print(n)
print()
print(m)
print()
print(n.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]

2


In [123]:
# Ex - 

m = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
n = m.reshape(3,2,3)
print(n)
print()
print(m)
print()
print(n.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

3


In [126]:
# Ex - 

x = np.array([[1,2,3,8],[4,5,6,20],[7,8,9,21]])
print(x)
print()
print(x.ndim)
print()
y = x.reshape(2,1,2,3)
print()
print(y)
print()
print(y.ndim)

[[ 1  2  3  8]
 [ 4  5  6 20]
 [ 7  8  9 21]]

2


[[[[ 1  2  3]
   [ 8  4  5]]]


 [[[ 6 20  7]
   [ 8  9 21]]]]

4


# Raval & Flatten - converts multi-dimentional array into 1-d array :-

In [128]:
# Ex -

m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("Dimention is : ",m.ndim)
print()

n = m.ravel()
print(n)
print("Now the new dimention is : ",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimention is :  3

[1 2 3 4 5 6 7 8 9]
Now the new dimention is :  1


In [129]:
# Ex -

m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("Dimention is : ",m.ndim)
print()

n = m.flatten()
print(n)
print("Now the new dimention is : ",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimention is :  3

[1 2 3 4 5 6 7 8 9]
Now the new dimention is :  1


# Create an array with diagonal elements filled with 1-identity matrix :-

In [131]:
# Ex - 

arr = np.eye(5)
print(arr)
print()
print(arr.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

2


In [132]:
# Ex - 

ar1 = np.eye(3,6)
print(ar1)
print()
print(ar1.ndim)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

2


In [2]:
# Ex - 

import numpy as np

ar1 = np.eye(5,8)
print(ar1)
print()
print(ar1.ndim)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]

2


# Create numpy arrays with random numbers :- (a.random.rand())

In [26]:
# Ex - 

import numpy as np

# rand() :- The random module's rand() method returns a random float between 0 & 1.

var = np.random.rand(5)
print(var)
print()
print(var.ndim)

[0.16063775 0.50111256 0.35532256 0.94545143 0.67260186]

1


In [27]:
# Ex - 

var = np.random.rand(3,2)
print(var)
print()
print(var.ndim)

[[0.70804713 0.40487476]
 [0.24876538 0.96088946]
 [0.45684604 0.65677907]]

2


In [28]:
# Ex - 

var = np.random.rand(3,2,5)
print(var)
print()
print(var.ndim)

[[[0.19622411 0.98340764 0.45173685 0.16033583 0.75408407]
  [0.32973468 0.15615032 0.22593774 0.59373697 0.6506235 ]]

 [[0.1020816  0.75961473 0.5301326  0.2591395  0.80218397]
  [0.94178206 0.73786628 0.79641783 0.42695478 0.41713001]]

 [[0.14328471 0.50930489 0.32443797 0.71651895 0.14057548]
  [0.32190731 0.63052039 0.01379929 0.33999025 0.4275524 ]]]

3


# randn() - The function is used to generate a value close to 0 and this may return positive or negative number as well.

In [30]:
# Ex - 

var = np.random.randn(5)
print(var)
print()
print("The dimention is : ",var.ndim)

[ 1.49846813  0.39367933  0.4873287  -0.3272619   0.20493926]

The dimention is :  1


In [31]:
# Ex - 

var = np.random.rand(2,5)
print(var)
print()
print("The dimention is : ",var.ndim)

[[0.87172661 0.8472317  0.13042603 0.7118844  0.10023529]
 [0.07046767 0.8721888  0.11899518 0.92562552 0.54822726]]

The dimention is :  2


In [34]:
# Ex - 

var = np.random.rand(3,2,5)
print(var)
print()
print("The dimention is :",var.ndim)
print("The shape is : ",var.shape)

[[[0.40289874 0.41267948 0.21623859 0.1924385  0.83838678]
  [0.83501217 0.34265268 0.95387538 0.28624394 0.84876799]]

 [[0.75571521 0.41180235 0.75897508 0.69280754 0.00910066]
  [0.95643556 0.26084341 0.27729576 0.1613941  0.43333645]]

 [[0.65374161 0.64105158 0.68620703 0.7300249  0.17879275]
  [0.7685299  0.17636778 0.99366951 0.60600158 0.69815784]]]

The dimention is : 3
The shape is :  (3, 2, 5)


# randint function :-

In [45]:
a = np.random.randint(4,100,8)
print(a)
print()
# print(a.ndim)

TypeError: 'list' object is not callable

# randf (-this function is used for doing random sampling in numpy, It returns an array to specified shape and fills it with random floats in the half open interval between 0 and 1.)

In [47]:
# Ex - 

x = np.random.ranf(4)
print(x)
print()
print(x.ndim)

[0.70124028 0.9935991  0.67692058 0.12609026]

1


# Data types in numpy :-

In [48]:
import numpy as np

In [51]:
# Ex-  

x = np.array([1,2,3,4])
print("The data type is : ",x.dtype)

The data type is :  int64


In [52]:
x1 = np.array([2.5,8.6,3.7,5.2,3.6])
print("The data type is : ",x1.dtype)

The data type is :  float64


In [53]:
y = np.array(["apple","c","horse","girl"])
print("The data type is : ",y.dtype)

The data type is :  <U5


In [59]:
y = np.array(["apple","c","horse","girl",3.2,5,8,9.8])
print("The data type is : ",y.dtype)                    # {u = unsigned}

The data type is :  <U32


# Converting one data type into another data type :-

In [61]:
# Ex - 

x = np.array([1,2,3,4,5], x.dtype)
print(x)
print(x.dtype)

x1 = np.array([1,2,3,4,5], dtype = np.int32)
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int16
[1 2 3 4 5]
int32


In [62]:
# Ex - 

x = np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1 = np.array([1,2,3,4,5], dtype = "f")
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float32


In [64]:
m = np.array([1,2,3,4])
print(m)
print(m.dtype)
m1 = np.float64(m)
print(m1)
print(m1.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64


In [66]:
m = np.array([1,2,3,4])
print(m)
print(m.dtype)
m1 = np.float64(m)
print(m1)
print(m1.dtype)
m2 = np.int64(m1)
print(m2)
print(m2.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64
[1 2 3 4]
int64


In [69]:
x = np.array([1,2,3,4])
y = x.astype(complex)            # Complex me change krne ke liye astype ka use krte hai.
print(x)
print(x.dtype)
print()
print(y)
print(y.dtype)

[1 2 3 4]
int64

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


# Arithmetic operations in numpy :-

# Addition :-

In [2]:
# Ex - 

import numpy as np

x = np.array([1,2,3,4,5])
y = x+3
print(y)

[4 5 6 7 8]


In [3]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = x+m
print(y)

[ 6  8 10 12 14]


In [4]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = np.add(x,m)
print(y)

[ 6  8 10 12 14]


# Subtraction :-

In [5]:
# Ex - 

x = np.array([1,2,3,4,5])
y = x-3
print(y)

[-2 -1  0  1  2]


In [6]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = x-m
print(y)

[-4 -4 -4 -4 -4]


In [7]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = np.subtract(x,m)
print(y)

[-4 -4 -4 -4 -4]


# Multiplication :-

In [8]:
x = np.array([1,2,3,4])
y = x*3
print(y)

[ 3  6  9 12]


In [9]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = x*m
print(y)

[ 5 12 21 32 45]


In [10]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = np.multiply(x,m)
print(y)

[ 5 12 21 32 45]


# Division :-

In [11]:
x = np.array([1,2,3,4])
y = x/3
print(y)

[0.33333333 0.66666667 1.         1.33333333]


In [12]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = np.divide(x,m)
print(y)

[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [13]:
x = np.array([1,2,3,4,5,])
m = np.array(([5,6,7,8,9]))
y = x/m
print(y)

[0.2        0.33333333 0.42857143 0.5        0.55555556]


# Modulus :-

In [14]:
x = np.array([1,2,3,4])
y = x%3
print(y)

[1 2 0 1]


In [18]:
x = np.array([1,2,3,4,5])
m = np.array(([5,6,7,8,9]))
y = np.mod(x,m)
print(y)

[1 2 3 4 5]


In [17]:
x = np.array([1,2,3,4,5])
m = np.array(([5,6,7,8,9]))
y = x%m
print(y)

[1 2 3 4 5]


# Reciprocal :-

In [20]:
a = np.array([23,25,28,30])
b = np.reciprocal(a)              # 1/23 = 0.00, 1/25 = 0.00, 1/28 = 0.00, 1/30 = 0.00
print(b)

[0 0 0 0]


# Arithmetic operations in 2-d array :-

In [21]:
# Ex - 

n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1+n2
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [22]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1-n2
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [23]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1*n2
print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


In [24]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1/n2
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Arithmetic operations in 3-d array :-

In [26]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1+n2
print(x)
print()
print(x.ndim)

[[[ 2  4  6  8]
  [10 12 14 16]]]

3


In [27]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1-n2
print(x)
print()
print(x.ndim)

[[[0 0 0 0]
  [0 0 0 0]]]

3


In [28]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1*n2
print(x)
print()
print(x.ndim)

[[[ 1  4  9 16]
  [25 36 49 64]]]

3


In [29]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1/n2
print(x)
print()
print(x.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

3


In [30]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1**n2
print(x)
print()
print(x.ndim)

[[[       1        4       27      256]
  [    3125    46656   823543 16777216]]]

3


# Arithmetic functions :-

# Max and Min alongwith index number :-

In [31]:
a = np.array([12,13,1,2,3,4,5,8,5,4,78,65])
print(np.max(a))
print(np.min(a))

78
1


In [33]:
a = np.array([12,13,1,2,3,4,5,8,5,4,78,65])
print(np.max(a), np.argmax(a))                 # argmax use for find index position.
print(np.min(a), np.argmin(a))                 # argmin use for find index position.

78 10
1 2


In [46]:
m = np.array([[14,150,16,17],[100,25,89,35]])
print(m)
print()
print(m.ndim)
print()
n = np.min(m,axis=0)
print(n)

[[ 14 150  16  17]
 [100  25  89  35]]

2

[14 25 16 17]


In [47]:
m = np.array([[14,150,16,17],[100,25,89,35]])
print(m)
print()
print(m.ndim)
print()
n = np.min(m,axis=1)
print(n)

[[ 14 150  16  17]
 [100  25  89  35]]

2

[14 25]


In [48]:
m = np.array([[14,150,16,17],[100,25,89,35]])
print(m)
print()
print(m.ndim)
print()
n = np.max(m,axis=0)
print(n)

[[ 14 150  16  17]
 [100  25  89  35]]

2

[100 150  89  35]


In [49]:
m = np.array([[14,150,16,17],[100,25,89,35]])
print(m)
print()
print(m.ndim)
print()
n = np.max(m,axis=1)
print(n)

[[ 14 150  16  17]
 [100  25  89  35]]

2

[150 100]


# Sqare root :-

In [50]:
a = np.array([12,13,14,15])
print(np.sqrt(a))

[3.46410162 3.60555128 3.74165739 3.87298335]


In [51]:
b = np.array([4,9,16,25])
print(np.sqrt(b))

[2. 3. 4. 5.]


In [53]:
a = np.array([[12,13,1,4,45],[9,64,81,25,13]])
print(np.sqrt(a))

[[3.46410162 3.60555128 1.         2.         6.70820393]
 [3.         8.         9.         5.         3.60555128]]


# Sin value and Cos value :-

In [54]:
a = np.array([1,2,3])
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [55]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.98935825  0.41211849 -0.54402111]]


In [56]:
a = np.array([1,2,3])
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [57]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [-0.14550003 -0.91113026 -0.83907153]]


# Cumsum function {Cumulative Sum} :-

In [59]:
a = np.array([1,2,3,4])
print(np.cumsum(a))                  # 1, 1+2 = 3, 3+3 = 6, 6+4 = 10

[ 1  3  6 10]


In [61]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.cumsum(a))                          # Countinue adding one by one elements.

[ 1  3  6 10 15 21 29 38 48]


# Broadcaasting numpy array :-

In [63]:
n1 = np.array([1,2,3,4])
n2 = np.array([2,3,5])        # Because n1 contain 4 elements and n2 contain only 3 elements.
print(n1.shape)
print(n2.shape)
x = n1-n2
print(x)

(4,)
(3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [68]:
n1 = np.array([1,2,3,4])
print(n1.shape)
print(n1)
print()
n2 = np.array([[1],[2],[3],[4]])
print(n2.shape)
print(n2)
print()
x = n1+n2
print(x)

(4,)
[1 2 3 4]

(4, 1)
[[1]
 [2]
 [3]
 [4]]

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [71]:
x = np.array([[4],[3]])
print(x.shape)
print(x)
print()

y = np.array([[6,7,3],[1,3,2]])
print(y.shape)
print(y)
print()

print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

(2, 1)
[[4]
 [3]]

(2, 3)
[[6 7 3]
 [1 3 2]]

[[10 11  7]
 [ 4  6  5]]

[[-2 -3  1]
 [ 2  0  1]]

[[24 28 12]
 [ 3  9  6]]

[[0.66666667 0.57142857 1.33333333]
 [3.         1.         1.5       ]]


In [73]:
x = np.array([[4],[3],[5]])
print(x.shape)
print(x)
print()

y = np.array([[6,7,8],[1,3,1],[4,5,6]])
print(y.shape)
print(y)
print()
print(x+y)

(3, 1)
[[4]
 [3]
 [5]]

(3, 3)
[[6 7 8]
 [1 3 1]
 [4 5 6]]

[[10 11 12]
 [ 4  6  4]
 [ 9 10 11]]


# Indexing in numpy arrays :- 

# 1-d array :-

In [77]:
x = np.array([10,11,12,13,14,15,45])
print(x[4])
print(x[5])
print(x[-3])

14
15
14


# 2-d array :-

In [79]:
x = np.array([[11,12],[13,14]])
print(x[1,0])  # 0       1      -----> Index

13


In [80]:
print(x[0,0])

11


In [81]:
print(x[0,1])

12


In [82]:
x = np.array([[4,5,6],[10,11,12],[13,14,15]])
print(x[1,2])

12


In [83]:
print(x[2,1])

14


# 3-d array :-

In [88]:
b = np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(b)
print()
print(b.ndim)
print()
print(b[1,1,0])

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]

3

17


In [89]:
print(b[0,1,0])

13


In [100]:
b = np.array([[[3,6,9],[12,15,18],[1,5,7]]])
print(b)
print()
print(b.ndim)
print()
print(b[0,1,2])

[[[ 3  6  9]
  [12 15 18]
  [ 1  5  7]]]

3

18


# 5-d array :-

In [102]:
a = np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(a)
print()
print(a.ndim)
print()
print(a[0,0,0,1,2])

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]

5

6


In [103]:
print(a[0,0,0,2,1])

8


# Slicing of numpy arrays :-

# 1-d array :-

In [105]:
# Ex-

a = np.array([11,12,13,14,15,16,17,18,19])
print(a[2:7])       # { a[start : End : Step"] }
print(a[2:7:2])

[13 14 15 16 17]
[13 15 17]


In [106]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0:5])

[1 2 3 4 5]


In [108]:
print(a[::-1])      # For reverse

[9 8 7 6 5 4 3 2 1]


# 2-d arrays :-

In [110]:
b = np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[1,1:4])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[21 22 23]


In [113]:
print(b[0,1:4])

[11 12 13]


In [114]:
print(b[1,0:5:2])

[20 22 24]


# 3-d array :-

In [116]:
a = np.array([[[1,2,3,7,9],[4,5,6,9,10],[7,8,9,1,2]]])
print(a)
print()
print(a[0,1,1:4])

[[[ 1  2  3  7  9]
  [ 4  5  6  9 10]
  [ 7  8  9  1  2]]]

[5 6 9]


In [117]:
print(a[0,2,::2])

[7 9 2]


In [118]:
print(a[0,2,::-1])

[2 1 9 8 7]


# Iterating numpy array :-

# 1-d array :-

In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(a.ndim)
print()
for i in a:
    print(i)

[1 2 3 4]
1

1
2
3
4


# 2-d array :-

In [5]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.ndim)
print()
for i in x:
    for j in i:
        print(j)

[[1 2 3 4]
 [5 6 7 8]]
2

1
2
3
4
5
6
7
8


# 3-d array :-

In [7]:
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)
print()
for i in x:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

1
2
3
4
5
6
7
8
9
10
11
12


# nditer function :-   Iterate the variable

In [8]:
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)
print()
for i in np.nditer(x):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

1
2
3
4
5
6
7
8
9
10
11
12


# For change data type.

In [25]:
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)
print()
for i in np.nditer(x, flags=['buffered'], op_dtypes = ['S']):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


# ndenumerate function :-   For find index positions

In [26]:
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for i in np.ndenumerate(x):
    print(i)

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 0, 3), np.int64(4))
((0, 1, 0), np.int64(5))
((0, 1, 1), np.int64(6))
((0, 1, 2), np.int64(7))
((0, 1, 3), np.int64(8))
((0, 2, 0), np.int64(9))
((0, 2, 1), np.int64(10))
((0, 2, 2), np.int64(11))
((0, 2, 3), np.int64(12))


In [28]:
x = np.array([[[2,5,6,7],[8,9,5,6],[2,3,5,6]]])
print(x)
print(x.ndim)
print()
for i in np.ndenumerate(x):
    print(i)

[[[2 5 6 7]
  [8 9 5 6]
  [2 3 5 6]]]
3

((0, 0, 0), np.int64(2))
((0, 0, 1), np.int64(5))
((0, 0, 2), np.int64(6))
((0, 0, 3), np.int64(7))
((0, 1, 0), np.int64(8))
((0, 1, 1), np.int64(9))
((0, 1, 2), np.int64(5))
((0, 1, 3), np.int64(6))
((0, 2, 0), np.int64(2))
((0, 2, 1), np.int64(3))
((0, 2, 2), np.int64(5))
((0, 2, 3), np.int64(6))


# Copy v/s view in numpy array :-

In [29]:
x = np.array([1,2,3,4,5,6])
v = x.view()
print(v)
print()
print(x)

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [34]:
x = np.array([1,2,3,4,5,6])
v = x.view()                 # view function does not create a new array.
x[3] = 56
print(v)
print()
print(x)

[ 1  2  3 56  5  6]

[ 1  2  3 56  5  6]


In [35]:
x = np.array([1,2,3,4,5,6])
v = x.copy()                 # copy function create a new array.
x[3] = 56
print(v)
print()
print(x)

[1 2 3 4 5 6]

[ 1  2  3 56  5  6]


In [36]:
x = np.array([1,2,3,4,5,6])
v = x.copy()
v[3] = 85
print(v)
print()
print(x)

[ 1  2  3 85  5  6]

[1 2 3 4 5 6]


# Join array :-

# Concatenate :-

In [37]:
x = np.array([1,2,3,4])
x1 = np.array([5,6,7,8])
v = np.concatenate((x,x1))
print(x)
print()
print(x1)
print()
print(v)

[1 2 3 4]

[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [38]:
x = np.array([[5,10,15,20],[3,6,9,12]])
x1 = np.array([[1,2,3,4],[80,87,89,90]])
print(x)
print()
print(x1)
print()
v = np.concatenate((x,x1),axis=1)     # axis = 1 mean concatenate via columns
print(v)

[[ 5 10 15 20]
 [ 3  6  9 12]]

[[ 1  2  3  4]
 [80 87 89 90]]

[[ 5 10 15 20  1  2  3  4]
 [ 3  6  9 12 80 87 89 90]]


In [39]:
x = np.array([[5,10,15,20],[3,6,9,12]])
x1 = np.array([[1,2,3,4],[80,87,89,90]])
print(x)
print()
print(x1)
print()
v = np.concatenate((x,x1),axis=0)     # axis = 0 mean concatenate via rows
print(v)

[[ 5 10 15 20]
 [ 3  6  9 12]]

[[ 1  2  3  4]
 [80 87 89 90]]

[[ 5 10 15 20]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [80 87 89 90]]


# Horizontal stack (hstack) // Vertical stack (vstack) // For Height according (dstack) :-

In [44]:
x = np.array([1,2,3,4])
x1 = np.array([5,6,7,8])
x2 = np.array([100,200,300,400])
print()

print("This is array : ",x)
print("This is array : ",x1)
print("This is array : ",x2)
print()
v = np.hstack((x,x1,x2))
print("This is hstack : ")
print(v)
print()
m = np.vstack((x,x1,x2))
print("This is vstack : ")
print(m)
print()
p = np.dstack((x,x1,x2))
print("This is dstack : ")
print(p)


This is array :  [1 2 3 4]
This is array :  [5 6 7 8]
This is array :  [100 200 300 400]

This is hstack : 
[  1   2   3   4   5   6   7   8 100 200 300 400]

This is vstack : 
[[  1   2   3   4]
 [  5   6   7   8]
 [100 200 300 400]]

This is dstack : 
[[[  1   5 100]
  [  2   6 200]
  [  3   7 300]
  [  4   8 400]]]


# split array :-

In [47]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print()
v = np.array_split(a,3)
print(v)
print(type(v))
print()
print(v[0])

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>

[1 2 3]


In [48]:
a = np.array([[1,2],[4,5],[6,7],[8,9]])
print(a)
print()
v = np.array_split(a,4,axis=1)    # 4 = element
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]

[array([[1],
       [4],
       [6],
       [8]]), array([[2],
       [5],
       [7],
       [9]]), array([], shape=(4, 0), dtype=int64), array([], shape=(4, 0), dtype=int64)]


In [49]:
a = np.array([[[1,2],[4,5],[6,7],[8,9]]])
print(a)
print()
v = np.array_split(a,4,axis=0)
print(v)

[[[1 2]
  [4 5]
  [6 7]
  [8 9]]]

[array([[[1, 2],
        [4, 5],
        [6, 7],
        [8, 9]]]), array([], shape=(0, 4, 2), dtype=int64), array([], shape=(0, 4, 2), dtype=int64), array([], shape=(0, 4, 2), dtype=int64)]


# Search array :-

In [1]:
import numpy as np

In [14]:
a = np.array([1,2,5,6,1,2,3,4,2,2])
x = np.where(a==3)                   # For find index position
print(x,a.dtype)

(array([6]),) int64


In [9]:
a = np.array([1,2,5,6,1,2,3,4,2,2])
x = np.where(a%2==0)
print(x)

(array([1, 3, 5, 7, 8, 9]),)


# Search sorted array :-

In [22]:
z = np.array([11,12,13,14,18,19])
x = np.searchsorted(z,15)         #  Result : Index number ke baad given element aana chaiye.
print(x)

4


In [23]:
z = np.array([11,12,13,14,18,19,22,23])
x = np.searchsorted(z,20)
print(x)

6


In [25]:
p = np.array([21,22,23,31,32,33])
n = np.searchsorted(p,[25,28,30])     # Index position 3 ke baad 25,28,30 elements aane chaiye.
print(n)

[3 3 3]


# Sort function :-

In [26]:
a = np.array([12,78,87,43,65,90,14,17,18,-1,-5,69])
print(np.sort(a))

[-5 -1 12 14 17 18 43 65 69 78 87 90]


In [27]:
b = np.array(['o','k','w','q','z','a','n','p','b'])
print(np.sort(b))

['a' 'b' 'k' 'n' 'o' 'p' 'q' 'w' 'z']


In [29]:
a = np.array([[48,56,12],[13,89,2],[-5,96,87]])
print(a)
print()
print(a.ndim)
print()
print(np.sort(a))

[[48 56 12]
 [13 89  2]
 [-5 96 87]]

2

[[12 48 56]
 [ 2 13 89]
 [-5 87 96]]


In [30]:
x = np.array([[[14,18,-9],[-2,36,15],[12,89,-100]]])
print(x)
print()
print(x.ndim)
print()
print(np.sort(x))

[[[  14   18   -9]
  [  -2   36   15]
  [  12   89 -100]]]

3

[[[  -9   14   18]
  [  -2   15   36]
  [-100   12   89]]]


# Filter array :-

In [31]:
a = np.array([12,14,1,61,8,1,6,16])
f = [True,False,False,True,True,False,True,True]
b = a[f]
print(b)

[12 61  8  6 16]


# Suffle array :-

In [34]:
k = np.array([12,14,15,1,8,8,14,56,89,100,78,455])
print("The array is : ",k)
np.random.shuffle(k)
print("Now the suffled array is : ",k)

The array is :  [ 12  14  15   1   8   8  14  56  89 100  78 455]
Now the suffled array is :  [ 14   1  56   8 100  89  14   8 455  78  12  15]


# Unique array :-

In [35]:
k = np.array([12,14,6,7,9,3,45,5,33,2,33,2,33,14,12,7,9])
print(k)
x = np.unique(k)
print(x)

[12 14  6  7  9  3 45  5 33  2 33  2 33 14 12  7  9]
[ 2  3  5  6  7  9 12 14 33 45]


In [37]:
b = np.array([12,14,6,7,9,3,45,5,33,2,33,2,33,14,12,7,9])
print(b)
print()
x = np.unique(k,return_index = True)
print(x)

[12 14  6  7  9  3 45  5 33  2 33  2 33 14 12  7  9]

(array([ 2,  3,  5,  6,  7,  9, 12, 14, 33, 45]), array([9, 5, 7, 2, 3, 4, 0, 1, 8, 6]))


In [38]:
k = np.array([12,14,6,7,9,3,45,5,33,2,33,2,33,14,12,7,9])
print(k)
print()
x = np.unique(k,return_index=True, return_counts=True)
print(x)

[12 14  6  7  9  3 45  5 33  2 33  2 33 14 12  7  9]

(array([ 2,  3,  5,  6,  7,  9, 12, 14, 33, 45]), array([9, 5, 7, 2, 3, 4, 0, 1, 8, 6]), array([2, 1, 1, 1, 2, 2, 2, 2, 3, 1]))


# Resize function :-

In [39]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.ndim)
print(a.shape)
b = np.resize(a,(3,2))
print("Now the size is : ")
print(b)
print("The dimention is : ",b.ndim)
print("The shape is : ",b.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)
Now the size is : 
[[1 2]
 [3 4]
 [5 6]]
The dimention is :  2
The shape is :  (3, 2)


# insert function :-

# 1-d array :-

In [41]:
n = np.array([1,2,3,4,5,6,7,8,9])
print(n)
v = np.insert(n,3,200)                # 3 = index number per 200 insert krna hai.
print(v)

[1 2 3 4 5 6 7 8 9]
[  1   2   3 200   4   5   6   7   8   9]


In [42]:
n = np.array([1,2,3,4,5,6,7,8,9])
print(n)
v = np.insert(n,(3,5),(20,40))
print(v)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3 20  4  5 40  6  7  8  9]


# 2-d array :-

In [43]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2]])
print(x)
print(x.ndim)
x1 = np.insert(x,2,24,axis=1)
print(x1)

[[2 7 9 6 8]
 [4 5 7 1 2]]
2
[[ 2  7 24  9  6  8]
 [ 4  5 24  7  1  2]]


In [44]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2]])
print(x)
print(x.ndim)
x1 = np.insert(x,2,24,axis=0)
print(x1)

[[2 7 9 6 8]
 [4 5 7 1 2]]
2
[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [24 24 24 24 24]]


In [46]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2]])
print(x)
print(x.ndim)
x2 = np.insert(x,2,[25,26,27,28,29],axis=0)
print(x2)

[[2 7 9 6 8]
 [4 5 7 1 2]]
2
[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [25 26 27 28 29]]


# append function :-

In [52]:
a = np.array([12,13,14])
x = np.append(a,3.5)
print(x)

[12.  13.  14.   3.5]


In [54]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2]])
m = np.append(x,[[-4,-5,-6,-7,-8]],axis=0)
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [-4 -5 -6 -7 -8]]


# Delete function :-

In [56]:
a = np.array([12,13,14,15])
print(a)
print()
d = np.delete(a,[1])
print(d)

[12 13 14 15]

[12 14 15]


In [57]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)
print()
m = np.delete(x,0,axis=0)
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 4  5  7  1  2]
 [50  0 65  6  7]]


# Matrix :-

In [58]:
a = np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [59]:
b = np.array([[1,2,3],[1,2,3]])
print(b)
print(type(b))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


# Arithmetic operations in matrix :-

In [60]:
# Ex-

print("We are taking about matrix.")

a = np.matrix([[1,2,3],[1,2,3]])
c = np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a+c)

We are taking about matrix.
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]


In [61]:
a = np.matrix([[1,2,3],[1,2,3]])
c = np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a-c)

[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[-3 -3 -3]
 [-3 -3 -3]]


In [65]:
# Ex-

print("We are talking about matrix.")

a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
print(a)
print()
print(b)
print()
l = a.dot(b)
print(l)

We are talking about matrix.
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]


In [67]:
print("We are talking about arrays.")

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print()
print(b)
print()
print(a*b)

We are talking about arrays.
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


# Matrix functions :-

# Transpose function :-

In [71]:
a = np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.transpose(a))
print()      # Or
print(a.T)

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


# Swapaxes function :-

In [75]:
a = np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.swapaxes(a,1,0))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


# Inverse function :-

In [76]:
a = np.matrix([[3,4],[2,1]])
print(a)
print()
print(np.linalg.inv(a))

[[3 4]
 [2 1]]

[[-0.2  0.8]
 [ 0.4 -0.6]]


# Power function :-

In [77]:
a = np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,2))
print()
print(np.linalg.matrix_power(a,0))
print()
print(np.linalg.matrix_power(a,-2))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]

[[1 0]
 [0 1]]

[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


# Diterminate :-

In [78]:
a = np.matrix([[1,3,5],[2,4,6],[10,11,12]])
print(a)
print()
print(np.linalg.det(a))

[[ 1  3  5]
 [ 2  4  6]
 [10 11 12]]

2.442490654175344e-16
